package bean;
// Generated 15/09/2023 22:23:57 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraProdutoBlf generated by hbm2java
 */
@Entity
@Table(name="compra_produto_blf"
    ,catalog="db_bruna_carvalho"
)
public class CompraProdutoBlf  implements java.io.Serializable {


     private int idCompraProdutoBlf;
     private CompraBlf compraBlf;
     private ProdutoBlf produtoBlf;
     private String quantidadeBlf;
     private String valorUnitarioBlf;

    public CompraProdutoBlf() {
    }

    public CompraProdutoBlf(int idCompraProdutoBlf, CompraBlf compraBlf, ProdutoBlf produtoBlf, String quantidadeBlf, String valorUnitarioBlf) {
       this.idCompraProdutoBlf = idCompraProdutoBlf;
       this.compraBlf = compraBlf;
       this.produtoBlf = produtoBlf;
       this.quantidadeBlf = quantidadeBlf;
       this.valorUnitarioBlf = valorUnitarioBlf;
    }
   
     @Id 

    
    @Column(name="id_compraProduto_blf", unique=true, nullable=false)
    public int getIdCompraProdutoBlf() {
        return this.idCompraProdutoBlf;
    }
    
    public void setIdCompraProdutoBlf(int idCompraProdutoBlf) {
        this.idCompraProdutoBlf = idCompraProdutoBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra", nullable=false)
    public CompraBlf getCompraBlf() {
        return this.compraBlf;
    }
    
    public void setCompraBlf(CompraBlf compraBlf) {
        this.compraBlf = compraBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto", nullable=false)
    public ProdutoBlf getProdutoBlf() {
        return this.produtoBlf;
    }
    
    public void setProdutoBlf(ProdutoBlf produtoBlf) {
        this.produtoBlf = produtoBlf;
    }

    
    @Column(name="quantidade_Blf", nullable=false, length=45)
    public String getQuantidadeBlf() {
        return this.quantidadeBlf;
    }
    
    public void setQuantidadeBlf(String quantidadeBlf) {
        this.quantidadeBlf = quantidadeBlf;
    }

    
    @Column(name="valorUnitario_Blf", nullable=false, length=45)
    public String getValorUnitarioBlf() {
        return this.valorUnitarioBlf;
    }
    
    public void setValorUnitarioBlf(String valorUnitarioBlf) {
        this.valorUnitarioBlf = valorUnitarioBlf;
    }




}


