package bean;
// Generated 15/09/2023 22:23:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraBlf generated by hbm2java
 */
@Entity
@Table(name="compra_blf"
    ,catalog="db_bruna_carvalho"
)
public class CompraBlf  implements java.io.Serializable {


     private int idCompraBlf;
     private FornecedorBlf fornecedorBlf;
     private UsuarioBlf usuarioBlf;
     private Date dataCompraBlf;
     private double totalCompraBlf;
     private String statusPagamentoBlf;
     private String metodoPagamentoBlf;
     private Set compraProdutoBlfs = new HashSet(0);

    public CompraBlf() {
    }

	
    public CompraBlf(int idCompraBlf, FornecedorBlf fornecedorBlf, UsuarioBlf usuarioBlf, Date dataCompraBlf, double totalCompraBlf, String statusPagamentoBlf, String metodoPagamentoBlf) {
        this.idCompraBlf = idCompraBlf;
        this.fornecedorBlf = fornecedorBlf;
        this.usuarioBlf = usuarioBlf;
        this.dataCompraBlf = dataCompraBlf;
        this.totalCompraBlf = totalCompraBlf;
        this.statusPagamentoBlf = statusPagamentoBlf;
        this.metodoPagamentoBlf = metodoPagamentoBlf;
    }
    public CompraBlf(int idCompraBlf, FornecedorBlf fornecedorBlf, UsuarioBlf usuarioBlf, Date dataCompraBlf, double totalCompraBlf, String statusPagamentoBlf, String metodoPagamentoBlf, Set compraProdutoBlfs) {
       this.idCompraBlf = idCompraBlf;
       this.fornecedorBlf = fornecedorBlf;
       this.usuarioBlf = usuarioBlf;
       this.dataCompraBlf = dataCompraBlf;
       this.totalCompraBlf = totalCompraBlf;
       this.statusPagamentoBlf = statusPagamentoBlf;
       this.metodoPagamentoBlf = metodoPagamentoBlf;
       this.compraProdutoBlfs = compraProdutoBlfs;
    }
   
     @Id 

    
    @Column(name="id_compra_blf", unique=true, nullable=false)
    public int getIdCompraBlf() {
        return this.idCompraBlf;
    }
    
    public void setIdCompraBlf(int idCompraBlf) {
        this.idCompraBlf = idCompraBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor_blf", nullable=false)
    public FornecedorBlf getFornecedorBlf() {
        return this.fornecedorBlf;
    }
    
    public void setFornecedorBlf(FornecedorBlf fornecedorBlf) {
        this.fornecedorBlf = fornecedorBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario_blf", nullable=false)
    public UsuarioBlf getUsuarioBlf() {
        return this.usuarioBlf;
    }
    
    public void setUsuarioBlf(UsuarioBlf usuarioBlf) {
        this.usuarioBlf = usuarioBlf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCompra_blf", nullable=false, length=10)
    public Date getDataCompraBlf() {
        return this.dataCompraBlf;
    }
    
    public void setDataCompraBlf(Date dataCompraBlf) {
        this.dataCompraBlf = dataCompraBlf;
    }

    
    @Column(name="totalCompra_blf", nullable=false, precision=10)
    public double getTotalCompraBlf() {
        return this.totalCompraBlf;
    }
    
    public void setTotalCompraBlf(double totalCompraBlf) {
        this.totalCompraBlf = totalCompraBlf;
    }

    
    @Column(name="statusPagamento_blf", nullable=false, length=10)
    public String getStatusPagamentoBlf() {
        return this.statusPagamentoBlf;
    }
    
    public void setStatusPagamentoBlf(String statusPagamentoBlf) {
        this.statusPagamentoBlf = statusPagamentoBlf;
    }

    
    @Column(name="metodoPagamento_blf", nullable=false, length=45)
    public String getMetodoPagamentoBlf() {
        return this.metodoPagamentoBlf;
    }
    
    public void setMetodoPagamentoBlf(String metodoPagamentoBlf) {
        this.metodoPagamentoBlf = metodoPagamentoBlf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compraBlf")
    public Set getCompraProdutoBlfs() {
        return this.compraProdutoBlfs;
    }
    
    public void setCompraProdutoBlfs(Set compraProdutoBlfs) {
        this.compraProdutoBlfs = compraProdutoBlfs;
    }




}


