package bean;
// Generated 27/10/2023 20:56:57 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraProdutoBlf generated by hbm2java
 */
@Entity
@Table(name="compra_produto_blf"
    ,catalog="db_bruna_carvalho"
)
public class CompraProdutoBlf  implements java.io.Serializable {


     private int idCompraProdutoBlf;
     private CompraBlf compraBlf;
     private ProdutoBlf produtoBlf;
     private int quantidadeBlf;
     private double valorUnitarioBlf;
  

    public CompraProdutoBlf() {
    }

    public CompraProdutoBlf(int idCompraProdutoBlf, CompraBlf compraBlf, ProdutoBlf produtoBlf, int quantidadeBlf, double valorUnitarioBlf) {
       this.idCompraProdutoBlf = idCompraProdutoBlf;
       this.compraBlf = compraBlf;
       this.produtoBlf = produtoBlf;
       this.quantidadeBlf = quantidadeBlf;
       this.valorUnitarioBlf = valorUnitarioBlf;
      
    }
   
     @Id @GeneratedValue(strategy=GenerationType.AUTO) 

    
    @Column(name="id_compraProduto_blf", unique=true, nullable=false)
    public int getIdCompraProdutoBlf() {
        return this.idCompraProdutoBlf;
    }
    
    public void setIdCompraProdutoBlf(int idCompraProdutoBlf) {
        this.idCompraProdutoBlf = idCompraProdutoBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra", nullable=false)
    public CompraBlf getCompraBlf() {
        return this.compraBlf;
    }
    
    public void setCompraBlf(CompraBlf compraBlf) {
        this.compraBlf = compraBlf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto", nullable=false)
    public ProdutoBlf getProdutoBlf() {
        return this.produtoBlf;
    }
    
    public void setProdutoBlf(ProdutoBlf produtoBlf) {
        this.produtoBlf = produtoBlf;
    }

    
    @Column(name="quantidade_Blf", nullable=false)
    public int getQuantidadeBlf() {
        return this.quantidadeBlf;
    }
    
    public void setQuantidadeBlf(int quantidadeBlf) {
        this.quantidadeBlf = quantidadeBlf;
    }

    
    @Column(name="valorUnitario_Blf", nullable=false, precision=10)
    public double getValorUnitarioBlf() {
        return this.valorUnitarioBlf;
    }
    
    public void setValorUnitarioBlf(double valorUnitarioBlf) {
        this.valorUnitarioBlf = valorUnitarioBlf;
    }
    
    




}


