package bean;
// Generated 15/09/2023 22:23:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FornecedorBlf generated by hbm2java
 */
@Entity
@Table(name="fornecedor_blf"
    ,catalog="db_bruna_carvalho"
)
public class FornecedorBlf  implements java.io.Serializable {


     private int idFornecedorBlf;
     private String cnpjBlf;
     private String empresaOuPessoaBlf;
     private String telefoneBlf;
     private String enderecoBlf;
     private String bairroBlf;
     private String cidadeBlf;
     private String ufBlf;
     private String cepBlf;
     private String emailBlf;
     private Set compraBlfs = new HashSet(0);

    public FornecedorBlf() {
    }

	
    public FornecedorBlf(int idFornecedorBlf, String cnpjBlf, String empresaOuPessoaBlf, String telefoneBlf, String enderecoBlf, String bairroBlf, String cidadeBlf, String ufBlf, String cepBlf, String emailBlf) {
        this.idFornecedorBlf = idFornecedorBlf;
        this.cnpjBlf = cnpjBlf;
        this.empresaOuPessoaBlf = empresaOuPessoaBlf;
        this.telefoneBlf = telefoneBlf;
        this.enderecoBlf = enderecoBlf;
        this.bairroBlf = bairroBlf;
        this.cidadeBlf = cidadeBlf;
        this.ufBlf = ufBlf;
        this.cepBlf = cepBlf;
        this.emailBlf = emailBlf;
    }
    public FornecedorBlf(int idFornecedorBlf, String cnpjBlf, String empresaOuPessoaBlf, String telefoneBlf, String enderecoBlf, String bairroBlf, String cidadeBlf, String ufBlf, String cepBlf, String emailBlf, Set compraBlfs) {
       this.idFornecedorBlf = idFornecedorBlf;
       this.cnpjBlf = cnpjBlf;
       this.empresaOuPessoaBlf = empresaOuPessoaBlf;
       this.telefoneBlf = telefoneBlf;
       this.enderecoBlf = enderecoBlf;
       this.bairroBlf = bairroBlf;
       this.cidadeBlf = cidadeBlf;
       this.ufBlf = ufBlf;
       this.cepBlf = cepBlf;
       this.emailBlf = emailBlf;
       this.compraBlfs = compraBlfs;
    }
   
     @Id 

    
    @Column(name="id_fornecedor_blf", unique=true, nullable=false)
    public int getIdFornecedorBlf() {
        return this.idFornecedorBlf;
    }
    
    public void setIdFornecedorBlf(int idFornecedorBlf) {
        this.idFornecedorBlf = idFornecedorBlf;
    }

    
    @Column(name="cnpj_blf", nullable=false, length=20)
    public String getCnpjBlf() {
        return this.cnpjBlf;
    }
    
    public void setCnpjBlf(String cnpjBlf) {
        this.cnpjBlf = cnpjBlf;
    }

    
    @Column(name="empresa_ou_pessoa_blf", nullable=false, length=45)
    public String getEmpresaOuPessoaBlf() {
        return this.empresaOuPessoaBlf;
    }
    
    public void setEmpresaOuPessoaBlf(String empresaOuPessoaBlf) {
        this.empresaOuPessoaBlf = empresaOuPessoaBlf;
    }

    
    @Column(name="telefone_blf", nullable=false, length=15)
    public String getTelefoneBlf() {
        return this.telefoneBlf;
    }
    
    public void setTelefoneBlf(String telefoneBlf) {
        this.telefoneBlf = telefoneBlf;
    }

    
    @Column(name="endereco_blf", nullable=false, length=40)
    public String getEnderecoBlf() {
        return this.enderecoBlf;
    }
    
    public void setEnderecoBlf(String enderecoBlf) {
        this.enderecoBlf = enderecoBlf;
    }

    
    @Column(name="bairro_blf", nullable=false, length=25)
    public String getBairroBlf() {
        return this.bairroBlf;
    }
    
    public void setBairroBlf(String bairroBlf) {
        this.bairroBlf = bairroBlf;
    }

    
    @Column(name="cidade_blf", nullable=false, length=25)
    public String getCidadeBlf() {
        return this.cidadeBlf;
    }
    
    public void setCidadeBlf(String cidadeBlf) {
        this.cidadeBlf = cidadeBlf;
    }

    
    @Column(name="uf_blf", nullable=false, length=2)
    public String getUfBlf() {
        return this.ufBlf;
    }
    
    public void setUfBlf(String ufBlf) {
        this.ufBlf = ufBlf;
    }

    
    @Column(name="cep_blf", nullable=false, length=10)
    public String getCepBlf() {
        return this.cepBlf;
    }
    
    public void setCepBlf(String cepBlf) {
        this.cepBlf = cepBlf;
    }

    
    @Column(name="email_blf", nullable=false, length=20)
    public String getEmailBlf() {
        return this.emailBlf;
    }
    
    public void setEmailBlf(String emailBlf) {
        this.emailBlf = emailBlf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedorBlf")
    public Set getCompraBlfs() {
        return this.compraBlfs;
    }
    
    public void setCompraBlfs(Set compraBlfs) {
        this.compraBlfs = compraBlfs;
    }




}


