package bean;
// Generated 27/10/2023 20:56:57 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdutoBlf generated by hbm2java
 */
@Entity
@Table(name="produto_blf"
    ,catalog="db_bruna_carvalho"
)
public class ProdutoBlf  implements java.io.Serializable {


     private int idProdutoBlf;
     private String nomeBlf;
     private String marcaBlf;
     private double precoBlf;
     private String tamanhoBlf;
     private int quantidadeBlf;
    

    public ProdutoBlf() {
    }

	
    public ProdutoBlf(int idProdutoBlf, String nomeBlf, String marcaBlf, double precoBlf, String tamanhoBlf, int quantidadeBlf) {
        this.idProdutoBlf = idProdutoBlf;
        this.nomeBlf = nomeBlf;
        this.marcaBlf = marcaBlf;
        this.precoBlf = precoBlf;
        this.tamanhoBlf = tamanhoBlf;
        this.quantidadeBlf = quantidadeBlf;
    }
    
   
     @Id 

    
    @Column(name="id_produto_blf", unique=true, nullable=false)
    public int getIdProdutoBlf() {
        return this.idProdutoBlf;
    }
    
    public void setIdProdutoBlf(int idProdutoBlf) {
        this.idProdutoBlf = idProdutoBlf;
    }

    
    @Column(name="nome_blf", nullable=false, length=35)
    public String getNomeBlf() {
        return this.nomeBlf;
    }
    
    public void setNomeBlf(String nomeBlf) {
        this.nomeBlf = nomeBlf;
    }

    
    @Column(name="marca_blf", nullable=false, length=30)
    public String getMarcaBlf() {
        return this.marcaBlf;
    }
    
    public void setMarcaBlf(String marcaBlf) {
        this.marcaBlf = marcaBlf;
    }

    
    @Column(name="preco_blf", nullable=false, precision=10)
    public double getPrecoBlf() {
        return this.precoBlf;
    }
    
    public void setPrecoBlf(double precoBlf) {
        this.precoBlf = precoBlf;
    }

    
    @Column(name="tamanho_blf", nullable=false, length=3)
    public String getTamanhoBlf() {
        return this.tamanhoBlf;
    }
    
    public void setTamanhoBlf(String tamanhoBlf) {
        this.tamanhoBlf = tamanhoBlf;
    }

    
    @Column(name="quantidade_blf", nullable=false)
    public int getQuantidadeBlf() {
        return this.quantidadeBlf;
    }
    
    public void setQuantidadeBlf(int quantidadeBlf) {
        this.quantidadeBlf = quantidadeBlf;
    }


    public String toString() {
        return getNomeBlf();
    }

     @Override
    public boolean equals(Object object) {
        if (object instanceof ProdutoBlf) {
            ProdutoBlf produtoBlf = (ProdutoBlf) object;
            if (this.getIdProdutoBlf()== produtoBlf.getIdProdutoBlf()) {
                    return true;
            } 
        }
         return false;
    
    }

}


