/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import bean.CompraBlf;
import bean.CompraProdutoBlf;
import bean.FornecedorBlf;
import bean.UsuarioBlf;
import dao.CompraProduto_DAO;
import dao.Compra_DAO;
import dao.Fornecedor_DAO;
import dao.Usuario_DAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
/**
 *
 * @author Bruna Lopes Freitas
 */
public class JDlgCompra extends javax.swing.JDialog {
    
     boolean incluindo;
     MaskFormatter MascaraData;
     CompraBlf compraBlf;
     Compra_DAO compra_DAO;
     CompraProduto_DAO compraProduto_DAO;
     CompraControle compraControle;
     CompraProdutoControle compraProdutoControle;
     CompraProdutoBlf compraProdutoBlf;
             
     
 

    /**
     * Creates new form JDlgPedidos
     */
    public JDlgCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Pedido");
        setLocationRelativeTo(null);
        
        //botoes
        habilitar(false);
  
     
        compraProduto_DAO = new CompraProduto_DAO();
        compra_DAO = new Compra_DAO();  
        compraProdutoControle = new CompraProdutoControle();
        List lista = new ArrayList();
        compraProdutoControle.setList(lista);
        jTablel.setModel(compraProdutoControle);
                

       
        //Cbox usuario
        Usuario_DAO usuario_DAO = new Usuario_DAO();
        List listaCliente = usuario_DAO.listAll();
        for (int i = 0; i < listaCliente.size(); i++) {
           jCboFkUsuario.addItem((UsuarioBlf)listaCliente.get(i));
        }
        //Cbox fornecedor
        Fornecedor_DAO fornecedor_DAO = new Fornecedor_DAO();
        List listaVendedor = fornecedor_DAO.listAll();
        for (int i = 0; i < listaVendedor.size(); i++) {
           jCboFKFornecedor.addItem((FornecedorBlf)listaVendedor.get(i));
        }
        
        
        //mascara data
         try {
            
             MascaraData = new MaskFormatter("##/##/####");
             
             
        } catch  (ParseException ex) {
            Logger.getLogger(JDlgUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       jFmtDataCompra.setFormatterFactory( new DefaultFormatterFactory(MascaraData) );
        
       
       
    }
    
       public void habilitar(boolean valor) {
        Util.habilitar(valor, jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(valor, jBtnIncluirProd, jBtnAlterarProd, jBtnExcluirProd);
        Util.habilitar(!valor, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }

       
    
    //viewBean campra
      public CompraBlf viewBean() {
        CompraBlf compraBlf = new CompraBlf();
        compraBlf.setIdCompraBlf(Util.strInt(jTxtCompra.getText())); 
        compraBlf.setFornecedorBlf((FornecedorBlf)jCboFKFornecedor.getSelectedItem()); 
        compraBlf.setUsuarioBlf((UsuarioBlf)jCboFkUsuario.getSelectedItem());
        compraBlf.setDataCompraBlf(Util.strDate(jFmtDataCompra.getText()));
        compraBlf.setTotalCompraBlf(Util.strDouble(jTxtTotal.getText()));
   
        return compraBlf;
    }
    
    //beanView compra
     public void beanView(CompraBlf compraBlf) {
        jTxtCompra.setText(Util.intStr(compraBlf.getIdCompraBlf()));   
        jFmtDataCompra.setText( Util.dateStr(compraBlf.getDataCompraBlf()));
        jCboFkUsuario.setSelectedItem(compraBlf.getUsuarioBlf());
        jCboFKFornecedor.setSelectedItem(compraBlf.getFornecedorBlf());
        jTxtTotal.setText(Util.doubleStr(compraBlf.getTotalCompraBlf()));  
    
        CompraProdutoControle compraProdutoControle = new CompraProdutoControle();
        List listProd = (List) compraProduto_DAO.listProd(compraBlf);
        compraProdutoControle.setList(listProd);
    }
     
       public int getSelectedRowProd() {
        return jTablel.getSelectedRow();
    }
       
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCompra = new javax.swing.JTextField();
        jFmtDataCompra = new javax.swing.JFormattedTextField();
        jTxtTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablel = new javax.swing.JTable();
        jBtnIncluirProd = new javax.swing.JToggleButton();
        jBtnAlterarProd = new javax.swing.JToggleButton();
        jBtnExcluirProd = new javax.swing.JToggleButton();
        jCboFkUsuario = new javax.swing.JComboBox<UsuarioBlf>();
        jCboFKFornecedor = new javax.swing.JComboBox<FornecedorBlf>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Num Compra");

        jLabel2.setText("Data");

        jLabel3.setText("Fornecedor");

        jLabel4.setText("Usuario");

        jLabel5.setText("Total");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnIncluir);

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setToolTipText("");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAlterar);

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnExcluir);

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnConfirmar);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancelar);

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnPesquisar);

        jTablel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitario", "Valor Total"
            }
        ));
        jScrollPane2.setViewportView(jTablel);

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });

        jCboFKFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboFKFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jFmtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jCboFKFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jCboFkUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluirProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnAlterarProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnExcluirProd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFmtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCboFKFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCboFkUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBtnIncluirProd)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAlterarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluirProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
         habilitar(true);

        Util.limparCampos(jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal, jBtnCancelar, jBtnConfirmar,jTablel);
        
        compraProdutoControle.setList(new ArrayList());
        jTxtCompra.grabFocus();
        incluindo = true;
        compraBlf = new CompraBlf();

        
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
          
         
        if (compraBlf != null) {
            Util.habilitar(true, jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor,jBtnCancelar, jBtnConfirmar, jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd);
            incluindo = false;
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
       
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
          if (compraBlf != null) {
            if (Util.perguntar("Deseja excluir o pedido ?") == true) {
              
               CompraProdutoBlf compraProdutoBlf;
                for (int linha = 0; linha < jTablel.getRowCount(); linha++) {
                    compraProdutoBlf = compraProdutoControle.getBean(linha);
                    compraProduto_DAO.delete(compraProdutoBlf);
                    
                }
                compra_DAO.delete(compraBlf);
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
       Util.limparCampos(jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal);
        

        
        
         
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
       compraBlf = viewBean();
        if (incluindo == true) {
            compra_DAO.insert(compraBlf);
            
            for (int linha = 0; linha < jTablel.getRowCount(); linha++) {
                compraProdutoBlf = compraProdutoControle.getBean(linha);
                compraProdutoBlf.setCompraBlf(compraBlf);
                compraProduto_DAO.insert(compraProdutoBlf);
            }
        } else {
            compra_DAO.update(compraBlf);
            //remover todos os pedidos produtos deste pedido
            
           for (int linha = 0; linha < jTablel.getRowCount(); linha++) {
                    compraProdutoBlf = compraProdutoControle.getBean(linha);
                    compraProdutoBlf.setCompraBlf(compraBlf);
                    compraProduto_DAO.delete(compraProdutoBlf);
                }

            //incluir todos os pedidosProduto que estao no jtable
           for (int linha = 0; linha < jTablel.getRowCount(); linha++) {
                compraProdutoBlf = compraProdutoControle.getBean(linha);
               
                compraProduto_DAO.insert(compraProdutoBlf);
        }
        habilitar(false);
        Util.limparCampos(jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal);
        compraProdutoControle.setList(new ArrayList());

        compraBlf = null;
        
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal, jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limparCampos(jTxtCompra, jFmtDataCompra, jCboFkUsuario,jCboFKFornecedor, jTxtTotal);
         compraProdutoControle.setList(new ArrayList());
         compraBlf = null;
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        
        JDlgCompraPesquisa jDlgCompraPesquisa = new JDlgCompraPesquisa(null, true);
        jDlgCompraPesquisa.setTelaAnterior(this);
        jDlgCompraPesquisa.setVisible(true);  
      
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgCompraProduto jDlgPedidosProduto = new JDlgCompraProduto(null, true);
        jDlgPedidosProduto.setTitle("Inclusão de Produtos");
        jDlgPedidosProduto.setTelaAnterior(this);
        jDlgPedidosProduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
       JDlgCompraProduto jDlgCompraProduto = new JDlgCompraProduto(null, true);
       jDlgCompraProduto.setTitle("Alteração de Produtos");
       jDlgCompraProduto.setTelaAnterior(this);
       int linSel = jTablel.getSelectedRow();
       compraProdutoBlf = (CompraProdutoBlf) compraProdutoControle.getBean(linSel);
       jDlgCompraProduto.beanView(compraProdutoBlf);
       jDlgCompraProduto.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        int linha = jTablel.getSelectedRow();
        if (linha == -1){
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if(Util.perguntar("Confirma exclusão do produto?") == true){
                compraProdutoControle.removeBean(linha);
            }
        }
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    private void jCboFKFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboFKFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboFKFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCompra dialog = new JDlgCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JToggleButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JToggleButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JToggleButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<FornecedorBlf> jCboFKFornecedor;
    private javax.swing.JComboBox<UsuarioBlf> jCboFkUsuario;
    private javax.swing.JFormattedTextField jFmtDataCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablel;
    private javax.swing.JTextField jTxtCompra;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
